version: "3"

services:
  nbxplorer:
    container_name: nbxplorer
    restart: always
    image: "nicolasdorier/nbxplorer:2.0.0.51"
    expose:
      - "32838"
    network_mode: "host"   
    environment:
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: btc
      NBXPLORER_SIGNALFILEDIR: /datadir
      NBXPLORER_NETWORK: mainnet
      NBXPLORER_BTCRPCURL: http://localhost:8332
      NBXPLORER_BTCNODEENDPOINT: localhost:8333
      NBXPLORER_BTCRPCUSER: ${BTCRPCUSER}
      NBXPLORER_BTCRPCPASSWORD: ${BTCRPCPASSWORD}
    volumes:
      - "nbxplorer_data:/datadir"

volumes: 
  nbxplorer_data:
